import java.util.List;
import java.util.Scanner;

/**
 * HumanPlayer class handles manual move selection by the user.
 * Requirement: Prompt the human player to choose the next move.
 */
public class HumanPlayer {
    private Scanner scanner;

    public HumanPlayer() {
        this.scanner = new Scanner(System.in);
    }

    /**
     * Displays available moves and prompts the user to select one.
     * * @param possibleMoves A list of moves generated by GameState[cite: 73, 74].
     * Format: (Piece Number * 100) + Destination Square.
     * @return The integer representing the chosen move.
     */
    public int chooseMove(List<Integer> possibleMoves) {
        System.out.println("\n--- Human Player's Turn ---");
        System.out.println("Available Moves:");

        // List all possible moves to the user
        for (int i = 0; i < possibleMoves.size(); i++) {
            int move = possibleMoves.get(i);
            int piece = move / 100;
            int destination = move % 100;
            System.out.println("[" + i + "] Piece " + piece + " to Square " + destination);
        }

        int choice = -1;
        while (true) {
            System.out.print("Select the index of your move (0-" + (possibleMoves.size() - 1) + "): ");
            
            // Validate that the input is an integer
            if (scanner.hasNextInt()) {
                choice = scanner.nextInt();
                
                // Validate that the choice is within the bounds of the list
                if (choice >= 0 && choice < possibleMoves.size()) {
                    break;
                } else {
                    System.out.println("Invalid index. Please choose a number between 0 and " + (possibleMoves.size() - 1) + ".");
                }
            } else {
                System.out.println("Invalid input. Please enter a valid integer index.");
                scanner.next(); // Clear the invalid input from the scanner
            }
        }

        return possibleMoves.get(choice);
    }
}